"""The ``rklb-value`` command-line entry point.

Usage::

    uv run rklb-value <config.yaml>            # full text report
    uv run rklb-value <config.yaml> --brief    # one-line GPU-first headline
    uv run rklb-value <config.yaml> --json     # typed JSON artifact
    uv run rklb-value --input-schema           # input schema (JSON)
    uv run rklb-value --default                # packaged default scenario
    uv run rklb-value --promote                # promote default public JSON bundle

The CLI reads a YAML config, runs the GPU-first valuation, and prints the
result. It is a thin shell over :mod:`data_center.config`,
:mod:`data_center.engine`, :mod:`data_center.json_output`, and
:mod:`data_center.text_report`.

Two output locations, by design (see the README section "Run output vs.
promoted model"):

* ``code/outputs/data_center/runs/`` is git-ignored scratch — redirect
  ``--json`` there and rerun freely; each run carries its own
  ``generated_at`` timestamp.
* ``data_center/models/space/`` holds reviewed space-model JSON artifacts.
* ``data_center/models/ground/`` holds reviewed ground-reference JSON artifacts.
* ``data_center/conclusion.md`` is a reviewed static conclusion and is not
  overwritten by promotion.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from .config import ValuationConfig, load_config
from .engine import run_valuation
from .ground import (
    build_ground_reference_output,
    default_ground_source_catalog,
    load_ground_config,
    render_ground_json,
)
from .json_output import PROMOTED_DEFAULT_ARTIFACT_ROLE, render_json
from .text_report import render_headline, render_text

# The calculator directory, resolved relative to this file so paths are found
# whether the package is run from a checkout or an installed wheel.
_CALCULATOR_DIR = Path(__file__).resolve().parents[2]
_PROJECT_DIR = _CALCULATOR_DIR.parent

# The packaged default scenario.
_DEFAULT_YAML = _CALCULATOR_DIR / "scenarios" / "default.yaml"
_GROUND_DEFAULT_YAML = _CALCULATOR_DIR / "scenarios" / "ground_default.yaml"

# The promoted public artifacts written by --promote. Scratch runs stay under
# code/outputs/data_center/runs/; data_center/models/space/ holds reviewed
# space-model JSON and data_center/models/ground/ holds the default ground
# reference. The static conclusion is not generated by this command.
_PROMOTED_MODEL_DIR = _PROJECT_DIR / "data_center" / "models" / "space"
_DEFAULT_OUTPUT_NAME = "default"
_OUTPUT_NAME_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]*")


def _repo_relative(path: Path) -> str:
    """Return a repository-relative path for public Markdown references."""
    try:
        return path.relative_to(_PROJECT_DIR).as_posix()
    except ValueError:
        return path.as_posix()


def _promoted_path(output_name: str) -> Path:
    """Return the promoted JSON model path for an output name.

    Args:
        output_name: File stem for the promoted JSON. The default stem is
            ``default`` and writes ``data_center/models/space/default.json``.

    Raises:
        ValueError: If ``output_name`` is not a safe file stem.
    """
    if _OUTPUT_NAME_PATTERN.fullmatch(output_name) is None:
        raise ValueError(
            "output name must start with a letter or number and contain only "
            "letters, numbers, underscores, or hyphens"
        )
    return _PROMOTED_MODEL_DIR / f"{output_name}.json"


def _promoted_ground_path(output_name: str) -> Path:
    """Return the promoted ground-reference JSON path for an output name."""
    _promoted_path(output_name)
    return _PROMOTED_MODEL_DIR.parent / "ground" / f"{output_name}.json"


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="rklb-value",
        description=(
            "GPU-first valuation calculator for Rocket Lab's orbital "
            "AI-inference data-center venture. Reads a YAML config and "
            "outputs per-year per-node economics."
        ),
    )
    parser.add_argument(
        "config",
        nargs="?",
        help=(
            "Path to the YAML config. Omit and pass --default to run the packaged default scenario."
        ),
    )
    parser.add_argument(
        "--default",
        action="store_true",
        help="Run the packaged default scenario (scenarios/default.yaml).",
    )
    parser.add_argument(
        "--brief",
        action="store_true",
        help="Print only the one-line GPU-first headline.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the typed JSON artifact instead of the text report.",
    )
    parser.add_argument(
        "--input-schema",
        action="store_true",
        help=("Print the GPU-first input schema (JSON) and exit. Needs no config."),
    )
    parser.add_argument(
        "--promote",
        action="store_true",
        help=(
            "Run a scenario and promote its JSON model into data_center/models/space/. "
            "The default output also writes data_center/models/ground/default.json. "
            "Defaults to the packaged default scenario."
        ),
    )
    parser.add_argument(
        "--output-name",
        default=_DEFAULT_OUTPUT_NAME,
        help=("Promoted JSON file stem. Defaults to 'default'."),
    )
    return parser


def _render_input_schema_json() -> str:
    """Render the GPU-first input schema as JSON.

    Dumps the :class:`data_center.config.ValuationConfig` schema — every
    field's type, bounds, default, and description. Emitted by
    `rklb-value --input-schema`.
    """
    return json.dumps(ValuationConfig.model_json_schema(), indent=2, ensure_ascii=False)


def _promote_model(config_path: Path, output_name: str) -> int:
    """Promote one scenario to public JSON artifacts.

    Regenerates a scenario through the engine and writes its typed JSON
    to the public ``data_center/models/space/`` workstream. For the default
    output name, it also writes the ground-reference JSON to
    ``data_center/models/ground/default.json``. This command does not
    overwrite ``data_center/conclusion.md``; that file is reviewed editorial
    prose tied to promoted JSON.

    Args:
        config_path: YAML scenario path to run. ``--promote`` defaults to
            the packaged scenario when no positional config is supplied.
        output_name: Promoted JSON file stem.

    Returns:
        A process exit code: ``0`` on success, ``1`` if the scenario fails
        to load or the output name is invalid.
    """
    try:
        model_path = _promoted_path(output_name)
        config: ValuationConfig = load_config(config_path)
        ground_config = (
            load_ground_config(_GROUND_DEFAULT_YAML)
            if output_name == _DEFAULT_OUTPUT_NAME
            else None
        )
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    artifact_role = (
        PROMOTED_DEFAULT_ARTIFACT_ROLE if output_name == _DEFAULT_OUTPUT_NAME else "promoted_named"
    )
    output = run_valuation(
        config,
        source_scenario_path=_repo_relative(config_path.resolve()),
        artifact_role=artifact_role,
    )
    model_path.parent.mkdir(parents=True, exist_ok=True)
    model_path.write_text(render_json(output) + "\n", encoding="utf-8")
    print(f"promoted model -> {model_path}", file=sys.stderr)
    if ground_config is not None:
        ground_output = build_ground_reference_output(
            output,
            ground_config,
            default_ground_source_catalog(),
        )
        ground_model_path = _promoted_ground_path(output_name)
        ground_model_path.parent.mkdir(parents=True, exist_ok=True)
        ground_model_path.write_text(render_ground_json(ground_output) + "\n", encoding="utf-8")
        print(f"promoted ground reference -> {ground_model_path}", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Returns a process exit code."""
    parser = _build_parser()
    args = parser.parse_args(argv)

    if args.input_schema:
        print(_render_input_schema_json())
        return 0

    if args.promote:
        promote_config = Path(args.config) if args.config else _DEFAULT_YAML
        return _promote_model(promote_config, str(args.output_name))

    if args.default:
        config_path: Path = _DEFAULT_YAML
    elif args.config:
        config_path = Path(args.config)
    else:
        parser.print_usage(sys.stderr)
        print(
            "error: provide a YAML config path, or use --default",
            file=sys.stderr,
        )
        return 2

    try:
        config: ValuationConfig = load_config(config_path)
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    output = run_valuation(config, source_scenario_path=_repo_relative(config_path.resolve()))

    if args.brief:
        print(render_headline(output))
    elif args.json:
        print(render_json(output))
    else:
        print(render_text(output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
